version: "3"

services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    # volumes:
    #   - "./scratch/data/redis:/data"
    expose:
      - 6379
  label-studio:
    container_name: labeling
    build: labeling
    environment:
      - MODEL_DIR=/data/models
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LABEL_STUDIO_USE_REDIS=true
    ports:
      - 9090:9090
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./scratch/data/server:/data"
      - "./scratch/logs:/tmp"
