version: "3"

services:

  redis:
    image: docker.io/redis:alpine
    container_name: redis
    hostname: redis
    expose:
      - 6379

  labeling:
    container_name: labeling
    image: docker.io/heartexlabs/label-studio:latest
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/dataset
      - LABEL_STUDIO_USE_REDIS=true
      - ML_TIMEOUT_HEALTH=30
      - ML_TIMEOUT_SETUP=30
    ports:
      - 8080:8080
    depends_on:
      - serving
    links:
      - serving
    volumes:
      - "./scratch:/dataset"
      - "label-studio:/label-studio/data"

  serving:
    container_name: serving
    build: serving
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/dataset
      - LABEL_STUDIO_USE_REDIS=true
      - MODEL_PATH=/data/models/model.h5
      - MODEL_DIR=/data/models
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - 9090
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./scratch:/dataset"
      - "./scratch/data/server:/data"

volumes:
  label-studio:
